### ISSUE TITLE
Bitsから10進数，16進数への変換を追加する

### ISSUE THREAD

**Issue by das08** [kanicreampasta/pybit-lib#18]
Bitsのメソッドに`to_dec`, `to_hex`を追加したい
返り値の型はstrの方が良さそう．．．？

**Comment by tinaxd** [comment]
やります

**Comment by tinaxd** [comment]
to_dec は signed int として解釈するということでOK?

**Comment by tinaxd** [comment]
16進数化の実装、速攻で終わらせます
